development:
  adapter: postgresql
  encoding: unicode
  database: photogram_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: photogram_test
  pool: 5
  timeout: 5000